leftnav:
- identifier: 397a97bf-4c76-04e7-9836-067e5723d8e2
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9de571c7-b4d9-964b-f04d-031509b5caf8
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: d631939e-d6b9-259b-8709-5c1a36b10de6
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 39a10e28-ce32-5d66-e070-11426a03a5c7
  name: Exams
  url: /pages/exams
  weight: 40
